version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  scraper:
    build: ./scraper
    container_name: webscraper
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - ./app/static/images:/app/images
      - tmp_data:/shared

  dash_app:
    build:
      context: ./app
      dockerfile: Dockerfile_dash_app
    volumes:
      - tmp_data:/shared
    ports:
      - "8050:8050"
    depends_on:
      - mongodb
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongodb:27017

volumes:
  mongo_data:
  tmp_data: 